<?php
/** op-module-develop:/index.phtml
 *
 * @created   2020-01-11
 * @version   1.0
 * @package   op-module-develop
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @created   2020-01-11
 */
namespace OP;

//	...
$args = OP()->Unit()->Router()->Args();
$cate = $args[0] ?? null;
$meta = $args[1] ?? null;
$name = $args[2] ?? null;
$file = $args[3] ?? null;

?>
<section>
	<div id="develop">
		<div class="flex">
			<div>
			<?php
			//	...
			switch( $cate ){
				//	...
				case 'phpinfo':
					include('phpinfo.php');
					break;

				case 'reference':
					$ext = 'md';
					break;

				case 'admin':
				case 'testcase':
				case 'sandbox':
					$ext = 'php';
					break;

				//	...
				default:
			}

			//	...
			if( $meta === 'app' ){
				$path = "asset:/{$cate}/{$name}.{$ext}";
			}else
			if( $meta === 'core' ){
				$path = "{$meta}:/{$cate}/{$name}.{$ext}";
			}else if( $file ?? null ){
				$path = "asset:/{$meta}/{$name}/{$cate}/{$file}.{$ext}";
			}else{
				$path = false;
			}

			//	...
			if( $path ){
				//	...
				if( $ext === 'md' ){
					OP()->Markdown($path);
				}else{
					OP()->Template($path);
				}
			}
			?>
			</div>
		</div>
	</div>
</section>

<!-- Markdown -->
<?php
//	...
OP()->WebPack()->Auto('./webpack/markdown.*');
//	...
$src = OP()->Env()->isLocalhost() ? OP()->MetaPath('develop:/vender/marked.js',true):'//cdn.jsdelivr.net/npm/marked/marked.min.js';
?>
<script src="<?= $src ?>"></script>

<!-- Syntax Highlight -->
<?php
$src = OP()->Env()->isLocalhost() ? OP()->MetaPath('develop:/vender/highlight.js',true):'//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js';
?>
<script src="<?= $src ?>"></script>
<!--
<link  href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/default.min.css" rel="stylesheet" />
 -->
