<?php
/** op-module-develop:/index.phtml
 *
 * @created   2020-01-11
 * @version   1.0
 * @package   op-module-develop
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @created   2020-01-11
 */
namespace OP;

?>
<section>
	<div id="develop">
		<?php OP::Template('menu.inc.php') ?>
		<hr/>
		<div class="flex">
			<div>
			<?php
			switch( OP()->Router()->Args()[0] ?? null ){
				case 'testcase':
					OP::Template('testcase.php');
					echo "<hr/>";
				//	break;

				case 'reference':
					OP::Template('reference.php');
					break;

				default:
					OP::Template('controller.inc.php');
			}
			?>
			</div>
			<div>
				<?php OP::Template('menu-right.phtml') ?>
			</div>
		</div>
	</div>
</section>

<?php if( OP::Config('execute')['markdown'] ): ?>
<!-- markdown -->
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<?php OP()->Unit('WebPack')->Auto('markdown.js'); ?>
<?php OP()->Unit('WebPack')->Auto('markdown.css'); ?>
<?php endif; ?>

<?php if( OP()->Config('execute')['highlight'] ): ?>
<!-- syntax highlight -->
<!--
<link  href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/default.min.css" rel="stylesheet" />
 -->
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js"></script>
<?php endif; ?>
