<?php
/** op-module-develop:/menu.phtml
 *
 * @created   2020-01-11
 * @version   1.0
 * @package   op-module-develop
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** controller.php
 * @deprecated
 */

/** namespace
 *
 * @created   2020-01-11
 */
namespace OP;

/* @var $app UNIT\App */

//	...
$root = ConvertURL('develop:/');

//	...
$list = ['phpinfo'];

//	...
foreach( glob(ConvertPath('asset:/unit/').'*', GLOB_ONLYDIR) as $path ){
	//	...
	if(!file_exists($path.'/develop') ){
		continue;
	}

	//	...
	$list[] = basename($path);
}

//	...
foreach( glob('*', GLOB_ONLYDIR) as $name ){
	//	...
	if( $name[0] === '_' ){
		continue;
	}

	//	...
	$list[] = $name;
}

?>
<section>
[
	<?php foreach( $list as $name ): ?>
	<span class="menu"><a href="<?= $root . $name ?>"><?= $name ?></a></span>
	<?php endforeach; ?>
]
</section>
