<?php
/**	op-module-develop:/tutorial.phtml
 *
 * @created    2025-07-26
 * @version    1.0
 * @package    op-module-develop
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	declare
 *
 */
declare(strict_types=0);

/**	namespace
 *
 */
namespace OP\DEVELOP;

?>
<!-- Tutorial guidance -->
<section data-translation="true">
	<h1>Tutorial</h1>
	<p>
		A tutorial is a method of transferring knowledge, often interactive, that teaches by example and practice.
		You can download and install the tutorial by entering the following command.
	</p>
	<!--
	<pre><code>php app.php _develop/git command=submodule/add type=module name=tutorial</code></pre>
	<p>
		You can also install it directly using Git commands without using the framework feature.
	</p>
	<pre><code>git submodule add https://github.com/TomoakiNagahara/op-module-tutorial.git asset/module/tutorial</code></pre>
	 -->
	<ol>
		<li>
			Move to the Git root: <br/>
			<code>cd <?= OP()->Path('git:/') ?></code>
		</li>
		<li>
			Enter the following command to add a tutorial submodule: <br/>
			<code>git submodule add https://github.com/onepiece-framework/op-module-tutorial.git asset/module/tutorial</code>
		</li>
		<li>
			Move to the develop directory: <br/>
			<code>cd <?= __DIR__ ?></code>
		</li>
		<li>
			Create an alias with the following command: <br/>
			<code>ln -s ../tutorial/content/ tutorial</code>
		</li>
		<li>
			Once you've completed the above steps, reload this page.
		</li>
	</ol>
</section>
<section data-translation="true">
	<h2>CI/CD</h2>
	<p>
		To reflect the downloaded and installed updates in the repository, use the <code>cicd</code> command.
	</p>
	<pre><code>./cicd</code></pre>
	<p>
		If you see an error saying you don’t have permission to push, use the following command to change the URL to your own repository.
	</p>
	<pre><code>git remote set-url origin https://github.com/{your-account}/op-skeleton-2030</code></pre>
</section>
<?php if( file_exists( OP()->Path('asset:/module/tutorial/content/index.php') ) ): ?>
<section data-translation="true">
	<h1>Discover more</h1>
	<p>Start the tutorial by clicking the link to the right: <a href="<?= OP()->URL('develop:/tutorial/') ?>">Tutorial</a></p>
</section>
<?php endif; ?>
