<?php
/** op-module-develop:/layout/menu/left.phtml
 *
 * @created   2024-02-05
 * @version   1.0
 * @package   op-module-develop
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 */
namespace OP\MODULE\DEVELOP;

//	...
$root = OP()->MetaPath('develop:/', true);
$args = OP()->Router()->Args();
$cate = $args[0] ?? null;
/*
$meta = $args[1] ?? null;
$name = $args[2] ?? null;
$file = $args[3] ?? null;
*/

//	...
if(!$cate or $cate === 'phpinfo' ){
	return;
}

?>
<section class="">
	<ul>
	<?php foreach(['core','unit','layout','module','webpack'] as $meta): ?>
		<li>
			<span class="<?= $meta === ($args[1] ?? null) ? 'bold': '' ?>">
				<?= $meta ?>
			</span>
			<ul>
			<?php foreach( GetUnitNameList($meta) as $name): ?>
				<li>
					<a href="<?= "{$root}{$cate}/{$meta}/{$name}" ?>">
						<span class="<?= $name === ($args[2] ?? null) ? 'bold': '' ?>"><?= $name ?></span>
					</a>
					<?php
					if( $name !== ($args[2] ?? null) ){
						continue;
					}
					?>
					<?php include(__DIR__.'/left-file.phtml') ?>
				</li>
			<?php endforeach; ?>
			</ul>
		</li>
	<?php endforeach; ?>
	</ul>
</section>
<?php

/**
 *
 */
function GetUnitNameList(string $meta){
	//	...
	if( $meta == 'core' ){
		return GetFileNameList($meta, '');
	}

	//	...
	$list = [];
	$path = OP()->MetaPath("{$meta}:/");
	$cate = OP()->Router()->Args()[0];

	//	...
	foreach( glob($path . '*') as $path ){
		//	...
		if( file_exists("{$path}/{$cate}/") === false ){
			continue;
		}

		//	...
		$list[] = basename($path);
	}

	//	...
	return $list;
}

/**
 *
 */
function GetFileNameList(string $meta, string $name){
	$list = [];
	$cate = OP()->Router()->Args()[0];
	$path = OP()->MetaPath("{$meta}:/$name");
	$ext  = ($cate === 'reference') ? 'md': 'php';
	foreach( glob("{$path}/{$cate}/*.{$ext}") as $path ){
		$list[] = basename($path, ".{$ext}");
	}
	return $list;
}
