<?php
/** op-module-develop:/layout/menu/top.phtml
 *
 * @created   2024-02-05
 * @version   1.0
 * @package   op-module-develop
 * @author    Tomoaki Nagahara
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 */
namespace OP;

//	...
$list = ['phpinfo','admin','selftest','testcase','reference'];

//	...
if( file_exists( OP::Path('asset:/module/tutorial') ) ){
	$list[] = 'tutorial';
}

?>
<section class="menu">
	<?php foreach( $list as $key ): ?>
	<span><a href="<?= OP()->URL("develop:/{$key}/") ?>"><?= $key ?></a></span>
	<?php endforeach; ?>
</section>
